[build]
  base = "status-frontend"
  publish = "build"
  command = "npm run build:production"

[context.production.environment]
  REACT_APP_API_URL = "https://status-api.yourdomain.com/api"
  REACT_APP_SOCKET_URL = "https://status-api.yourdomain.com"
  REACT_APP_ENVIRONMENT = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
